apiVersion: 1

datasources:
  - name: tife-Prometheus
    type: prometheus
    access: proxy
    url: http://tife-prometheus:9090
    editable: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
          
  - name: tife_Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tife-tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
      nodeGraph:
        enabled: true
        
  - name: tife-Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://tife-tempo:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      derivedFields:
        -   datasourceUid: tempo
            matcherRegex: \[.+,(.+?),
            name: TraceID
            url: $${__value.raw}